apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
      version: blue
  template:
    metadata:
      labels:
        app: flask
        version: blue
    spec:
      containers:
        - name: flask
          image: sukanya996/web:05
          ports:
            - containerPort: 5000
         resources:
           requests:
             cpu: "0.5"
             memory: "100Mi"
             ephemeral-storage: "2Gi"
         limits:
           cpu: "1"
           memory: "200Mi"
           ephemeral-storage: "4Gi"

