apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: sukanya996/blue:green:green-47
        #image: sukanya996/image:1  # Use Harness variable if needed
        ports:
        - containerPort: 5000
