apiVersion: v1
kind: Service
metadata:
  name: flask-service-stage
  annotations:
    harness.io/stage-service: "true"
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
