apiVersion: v1
kind: Service
metadata:
  name: flask-service
  annotations:
    harness.io/primary-service: "true"
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
